<h1><h1 style= "color:teal;">Model Exercise</h1>
    <p style="color:turquoise;">
In this exercise, we'll continue working with the titanic dataset and building logistic regression models. Throughout this exercise, be sure you are training, evaluation, and comparing models on the train and validate datasets. The test dataset should only be used for your final model.

For all of the models you create, choose a threshold that optimizes for accuracy.

Do your work for these exercises in either a notebook or a python script named model within your classification-exercises repository. Add, commit, and push your work. </p>
    
<ol style: "color:SeaGreen;">




<li>Try out other combinations of features and models. </li>

<li>Use you best 3 models to predict and evaluate on your validate sample. </li>

<li>Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train? </li>

<li>Bonus1 How do different strategies for handling the missing values in the age column affect model performance?</li>

<li>Bonus2: How do different strategies for encoding sex affect model performance?</li>

<li>Bonus3: scikit-learn's LogisticRegression classifier is actually applying a regularization penalty to the coefficients by default. This penalty causes the magnitude of the coefficients in the resulting model to be smaller than they otherwise would be. This value can be modified with the C hyper parameter. Small values of C correspond to a larger penalty, and large values of C correspond to a smaller penalty.
    
Try out the following values for C and note how the coefficients and the model's performance on both the dataset it was trained on and on the validate split are affected.<br>
C=.01,.1,1,10,100,1000 </li>
<li> Bonus Bonus: how does scaling the data interact with your choice of C? </li>
    </ol>

In [55]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import statsmodels.formula.api as smf


import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# ignore warnings
import warnings
warnings.filterwarnings("ignore")



In [56]:
titanic= pd.read_csv("titanic.csv")
titanic.dropna(inplace=True)
titanic.head(2)

Unnamed: 0  passenger_id  survived  pclass     sex   age  sibsp  parch  \
1           1             1         1       1  female  38.0      1      0   
3           3             3         1       1  female  35.0      1      0   

      fare embarked  class deck  embark_town  alone  
1  71.2833        C  First    C    Cherbourg      0  
3  53.1000        S  First    C  Southampton      0

<li>Create another model that includes age in addition to fare and pclass. Does this model perform better than your previous one? </li>

In [93]:
X = titanic[['pclass','age','fare']]
y = titanic[['survived']]

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .20, random_state = 123)

X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size = .30, random_state = 123)


print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)



train:  (101, 3) , validate:  (44, 3) , test:  (37, 3)
train:  (101, 1) , validate:  (44, 1) , test:  (37, 1)


In [96]:
## Create the logistic regression object
logit = LogisticRegression(C=1, class_weight={0:1, 1:99}, random_state=123, intercept_scaling=1, solver='lbfgs')

In [97]:
## Fit the model to the training data
logit.fit(X_train, y_train)

LogisticRegression(C=1, class_weight={0: 1, 1: 99}, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [98]:
## Print the coefficients and intercept of the model
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)

Coefficient: 
 [[-0.53817351 -0.07690244  0.00671826]]
Intercept: 
 [8.16080691]


In [99]:
X_train.columns

Index(['pclass', 'age', 'fare'], dtype='object')

In [100]:
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
y_pred_proba

array([[9.78367950e-03, 9.90216321e-01],
       [4.56900311e-03, 9.95430997e-01],
       [8.76355108e-04, 9.99123645e-01],
       [1.81117517e-03, 9.98188825e-01],
       [3.30877322e-03, 9.96691227e-01],
       [4.31388667e-03, 9.95686113e-01],
       [9.23826314e-03, 9.90761737e-01],
       [4.89918870e-04, 9.99510081e-01],
       [1.45480631e-03, 9.98545194e-01],
       [1.80619956e-02, 9.81938004e-01],
       [4.61765488e-03, 9.95382345e-01],
       [9.38762856e-04, 9.99061237e-01],
       [4.10328708e-03, 9.95896713e-01],
       [1.62142823e-02, 9.83785718e-01],
       [1.89669833e-04, 9.99810330e-01],
       [8.57839590e-04, 9.99142160e-01],
       [3.34983586e-04, 9.99665016e-01],
       [4.31892031e-03, 9.95681080e-01],
       [1.03833461e-02, 9.89616654e-01],
       [4.94222813e-03, 9.95057772e-01],
       [1.55270462e-02, 9.84472954e-01],
       [1.15187242e-02, 9.88481276e-01],
       [2.32489082e-03, 9.97675109e-01],
       [2.14924298e-02, 9.78507570e-01],
       [3.706290

In [62]:
# accuracy
logit.score(X_train, y_train)

0.6336633663366337

In [101]:
# confusion matrix
print(confusion_matrix(y_train, y_pred))

[[ 0 37]
 [ 0 64]]


In [102]:
# classification report
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        37
           1       0.63      1.00      0.78        64

    accuracy                           0.63       101
   macro avg       0.32      0.50      0.39       101
weighted avg       0.40      0.63      0.49       101



<li>Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model. </li>

In [66]:
titanic['gender'] = titanic.sex == 'female'
titanic.head(1)

Unnamed: 0  passenger_id  survived  pclass     sex   age  sibsp  parch  \
1           1             1         1       1  female  38.0      1      0   

      fare embarked  class deck embark_town  alone  gender  
1  71.2833        C  First    C   Cherbourg      0    True

In [77]:
X = titanic[['age','fare', 'gender']]
y = titanic[['survived']]

X_train_validate, X_test, y_train_validate, y_test = train_test_split(X, y, test_size = .20, random_state = 123)

X_train, X_validate, y_train, y_validate = train_test_split(X_train_validate, y_train_validate, test_size = .30, random_state = 123)


print("train: ", X_train.shape, ", validate: ", X_validate.shape, ", test: ", X_test.shape)
print("train: ", y_train.shape, ", validate: ", y_validate.shape, ", test: ", y_test.shape)


train:  (101, 3) , validate:  (44, 3) , test:  (37, 3)
train:  (101, 1) , validate:  (44, 1) , test:  (37, 1)


In [87]:
logit2 = logit.fit(X_train, y_train)

In [89]:
print('Coefficient: \n', logit2.coef_)
print('Intercept: \n', logit2.intercept_)

Coefficient: 
 [[-7.43719410e-02 -9.26884603e-04  2.37922383e+00]]
Intercept: 
 [7.04768651]


In [80]:
X_train.columns

Index(['age', 'fare', 'gender'], dtype='object')

In [90]:
y_pred = logit2.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
y_pred_proba

array([[2.78367147e-02, 9.72163285e-01],
       [1.34237939e-02, 9.86576206e-01],
       [1.12406759e-04, 9.99887593e-01],
       [6.03594826e-03, 9.93964052e-01],
       [7.15780934e-03, 9.92842191e-01],
       [9.83490397e-04, 9.99016510e-01],
       [5.58929407e-03, 9.94410706e-01],
       [5.68133951e-04, 9.99431866e-01],
       [4.12508470e-04, 9.99587492e-01],
       [4.78115113e-03, 9.95218849e-01],
       [1.92098423e-03, 9.98079016e-01],
       [3.65479482e-03, 9.96345205e-01],
       [1.17358164e-03, 9.98826418e-01],
       [2.92065108e-03, 9.97079349e-01],
       [1.07024704e-03, 9.98929753e-01],
       [3.39995449e-03, 9.96600046e-01],
       [3.91542822e-04, 9.99608457e-01],
       [4.15661042e-03, 9.95843390e-01],
       [1.09112358e-02, 9.89088764e-01],
       [1.57021155e-02, 9.84297885e-01],
       [4.12307185e-03, 9.95876928e-01],
       [1.32684149e-02, 9.86731585e-01],
       [6.90538100e-03, 9.93094619e-01],
       [4.81754514e-02, 9.51824549e-01],
       [7.667301

In [91]:
# accuracy
logit2.score(X_train, y_train)

0.6336633663366337

In [84]:
# confusion matrix
print(confusion_matrix(y_train, y_pred))

[[ 0 37]
 [ 0 64]]


In [85]:
# classification report
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        37
           1       0.63      1.00      0.78        64

    accuracy                           0.63       101
   macro avg       0.32      0.50      0.39       101
weighted avg       0.40      0.63      0.49       101



In [103]:
y_pred1 = logit.predict(X_validate)
y_pred2 = logit2.predict(X_validate)

print("Model 1: solver = lbfgs, c = 1")

print('Accuracy: {:.2f}'.format(logit.score(X_validate, y_validate)))

print(confusion_matrix(y_validate, y_pred1))

print(classification_report(y_validate, y_pred1))

print("Model 2: solver = lbfgs, c = .1")

print('Accuracy: {:.2f}'.format(logit2.score(X_validate, y_validate)))

print(confusion_matrix(y_validate, y_pred2))

print(classification_report(y_validate, y_pred2))

Model 1: solver = lbfgs, c = 1
Accuracy: 0.66
[[ 0 15]
 [ 0 29]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.66      1.00      0.79        29

    accuracy                           0.66        44
   macro avg       0.33      0.50      0.40        44
weighted avg       0.43      0.66      0.52        44

Model 2: solver = lbfgs, c = .1
Accuracy: 0.66
[[ 0 15]
 [ 0 29]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.66      1.00      0.79        29

    accuracy                           0.66        44
   macro avg       0.33      0.50      0.40        44
weighted avg       0.43      0.66      0.52        44



In [ ]:
!git add 